# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/leopoldabgn"

[social.params]
icon = "brand-github"

[[social]]
identifier = "hackthebox"
name = "HackTheBox"
url = "https://app.hackthebox.com/users/1676673"

[social.params]
icon = "logo-htb"

[[social]]
identifier = "rootme"
name = "RootMe"
url = "https://www.root-me.org/sl0wguy"

[social.params]
icon = "logo-rootme-inverted-little"
